import { nextSighting, normalizePlate, validPlate } from './pattern';
const KEY = 'autoscan-demo-v1';
export const demoCommunity = { id:'demo-los-olivos', name:'Los Olivos', zone:'Samborondón, Guayas', role:'admin', camera:{name:'Acceso principal',url:'rtsp://camara-demo/stream'}, members:24 };
const initial = () => ({community:demoCommunity, vehicles:[{id:'v1',plate:'GBA-4821',owner:'María González',model:'Toyota Corolla',color:'Gris',createdAt:Date.now()},{id:'v2',plate:'GSC-1904',owner:'Carlos Mendoza',model:'Kia Sportage',color:'Blanco',createdAt:Date.now()},{id:'v3',plate:'GTD-7032',owner:'Ana Torres',model:'Chevrolet Onix',color:'Azul',createdAt:Date.now()}],events:[{id:'seed1',plate:'GBA-4821',owner:'María González',type:'recognized',status:'Reconocido',createdAt:Date.now()-180000},{id:'seed2',plate:'PBC-1234',type:'unknown',status:'En observación',count:2,createdAt:Date.now()-1800000}],patterns:{'PBC-1234':{times:[Date.now()-86400000,Date.now()-1800000],lastAlert:0}}});
export function loadDemo(){try{return JSON.parse(localStorage.getItem(KEY)) || initial();}catch{return initial();}}
export function saveDemo(state){localStorage.setItem(KEY,JSON.stringify(state));}
export async function hashAnswer(answer,salt){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(salt+':'+answer.trim().toLocaleLowerCase('es')));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
export async function demoProfile(name='María González',question='¿Cómo se llama tu primera mascota?',answer='luna'){const salt=crypto.randomUUID();return {uid:crypto.randomUUID(),name,question,salt,answerHash:await hashAnswer(answer,salt)};}
export function processDemo(state,plate){plate=normalizePlate(plate);if(!validPlate(plate))throw new Error('Formato de placa inválido');const now=Date.now();const vehicle=state.vehicles.find(v=>v.plate===plate);let result;let patterns={...state.patterns};let events=[...state.events];if(vehicle){result={id:crypto.randomUUID(),type:'recognized',status:'Reconocido',owner:vehicle.owner,plate,createdAt:now};}else{const next=nextSighting(patterns[plate],now);patterns[plate]={times:next.times,lastAlert:next.shouldAlert?now:patterns[plate]?.lastAlert||0};result={id:crypto.randomUUID(),type:next.shouldAlert?'pattern_detected':'unknown',status:next.shouldAlert?'Pendiente':'En observación',plate,count:next.count,createdAt:now};}events.unshift(result);return {state:{...state,patterns,events:events.slice(0,300)},result};}
