const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {onObjectFinalized}=require('firebase-functions/v2/storage');
const {onDocumentCreated}=require('firebase-functions/v2/firestore');
const admin=require('firebase-admin');
const vision=require('@google-cloud/vision');
const {randomBytes,createHash}=require('node:crypto');
const {mkdtemp,readFile,rm}=require('node:fs/promises');
const {tmpdir}=require('node:os');
const path=require('node:path');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const ffmpeg=require('ffmpeg-static');
const {secretHash,matches,extractPlates,pattern}=require('./core.cjs');
admin.initializeApp();
const db=admin.firestore(),visionClient=new vision.ImageAnnotatorClient(),exec=promisify(execFile);
const options={region:'us-central1'};
const stamp=()=>admin.firestore.FieldValue.serverTimestamp();
function uid(request){if(!request.auth)throw new HttpsError('unauthenticated','Inicia sesión.');return request.auth.uid;}
function text(value,max=150){if(typeof value!=='string'||!value.trim()||value.length>max)throw new HttpsError('invalid-argument','Revisa los campos del formulario.');return value.trim();}
function communityId(request){const id=text(request.data.communityId,128);if(!/^[\w-]+$/.test(id))throw new HttpsError('invalid-argument','Comunidad inválida.');return id;}
async function member(id,user,adminOnly=false){const snap=await db.doc(`communities/${id}/members/${user}`).get();if(!snap.exists||(adminOnly&&snap.data().role!=='admin'))throw new HttpsError('permission-denied','No tienes acceso a esta comunidad.');return snap.data();}
async function quota(user,key,limit,windowMs){const ref=db.doc(`rate_limits/${user}_${key}`);await db.runTransaction(async tx=>{const snap=await tx.get(ref),now=Date.now(),old=snap.data();const count=old&&now-old.start<windowMs?old.count+1:1;if(count>limit)throw new HttpsError('resource-exhausted','Demasiados intentos. Espera unos minutos.');tx.set(ref,{count,start:count===1?now:old.start});});}
const inviteDigest=code=>createHash('sha256').update(code.toUpperCase()).digest('hex');
function invitation(){return randomBytes(6).toString('base64url').replace(/[-_]/g,'A').slice(0,6).toUpperCase();}
exports.saveProfile=onCall(options,async request=>{const user=uid(request);await quota(user,'profile',10,3600000);const name=text(request.data.name,80),question=text(request.data.question,150),answer=text(request.data.answer,100);const secret=secretHash(answer);await db.doc(`user_secrets/${user}`).set({question,...secret});await db.doc(`users/${user}`).set({name,question},{merge:true});return {ok:true};});
exports.createCommunity=onCall(options,async request=>{const user=uid(request);await quota(user,'create',5,3600000);const name=text(request.data.name,80),zone=text(request.data.zone,150),ref=db.collection('communities').doc(),code=invitation(),digest=inviteDigest(code);const community={communityId:ref.id,name,zone,createdBy:user,timestamp:stamp()};await db.runTransaction(async tx=>{const existing=await tx.get(db.doc(`invitations/${digest}`));if(existing.exists)throw new HttpsError('aborted','Vuelve a intentar crear la comunidad.');tx.set(ref,community);tx.set(ref.collection('members').doc(user),{communityId:ref.id,uid:user,role:'admin',timestamp:stamp()});tx.set(db.doc(`invitations/${digest}`),{communityId:ref.id});tx.set(db.doc(`community_secrets/${ref.id}`),{inviteHash:digest});tx.set(db.doc(`users/${user}`),{communityId:ref.id},{merge:true});});return {community:{id:ref.id,name,zone,role:'admin'},code};});
exports.rotateInvite=onCall(options,async request=>{const user=uid(request),id=communityId(request);await member(id,user,true);await quota(user,'invite',10,3600000);const code=invitation(),digest=inviteDigest(code),ref=db.doc(`community_secrets/${id}`);await db.runTransaction(async tx=>{const old=await tx.get(ref),collision=await tx.get(db.doc(`invitations/${digest}`));if(collision.exists)throw new HttpsError('aborted','Vuelve a generar el código.');if(old.data()?.inviteHash)tx.delete(db.doc(`invitations/${old.data().inviteHash}`));tx.set(ref,{inviteHash:digest});tx.set(db.doc(`invitations/${digest}`),{communityId:id});});return {code};});
exports.joinCommunity=onCall(options,async request=>{const user=uid(request);await quota(user,'join',10,600000);const code=text(request.data.code,6);if(!/^[A-Z0-9]{6}$/i.test(code))throw new HttpsError('invalid-argument','Código inválido.');return db.runTransaction(async tx=>{const invite=await tx.get(db.doc(`invitations/${inviteDigest(code)}`));if(!invite.exists)throw new HttpsError('not-found','El código no es válido.');const id=invite.data().communityId,ref=db.doc(`communities/${id}`),memberRef=ref.collection('members').doc(user);const [community,existing]=await Promise.all([tx.get(ref),tx.get(memberRef)]);if(!community.exists)throw new HttpsError('not-found','Comunidad no encontrada.');if(!existing.exists)tx.set(memberRef,{communityId:id,uid:user,role:'resident',timestamp:stamp()});tx.set(db.doc(`users/${user}`),{communityId:id},{merge:true});return {community:{...community.data(),timestamp:null,id,role:existing.data()?.role||'resident'}};});});
exports.saveCamera=onCall(options,async request=>{const user=uid(request),id=communityId(request);await member(id,user,true);const name=text(request.data.name,80),url=text(request.data.url,1000);if(!/^rtsps?:\/\//i.test(url))throw new HttpsError('invalid-argument','URL RTSP inválida.');await db.doc(`camera_secrets/${id}`).set({communityId:id,url,name});await db.doc(`communities/${id}`).update({camera:{name}});/* Producción: un gateway ONVIF/RTSP autorizado debe ingerir el stream y subir clips a cameras/{communityId}/. No se conecta desde el navegador ni se exponen credenciales RTSP a residentes. */return {ok:true};});
async function recordSighting(id,plate,eventId,simulated=false){const community=await db.doc(`communities/${id}`).get();if(!community.exists)throw new Error('Comunidad no encontrada');const known=await db.collection('vehicles').where('communityId','==',id).where('plate','==',plate).limit(1).get();const logRef=db.doc(`sighting_logs/${eventId}`),patternRef=db.doc(`unrecognized_sightings/${id}_${plate}`);return db.runTransaction(async tx=>{const log=await tx.get(logRef);if(log.exists)return log.data();const now=Date.now();if(!known.empty){const result={communityId:id,plate,owner:known.docs[0].data().owner,type:'recognized',status:'Reconocido',timestamp:stamp(),simulated};tx.set(logRef,result);return {...result,createdAt:now};}const old=await tx.get(patternRef),next=pattern(old.data(),now);const result={communityId:id,plate,count:next.count,type:next.alert?'pattern_detected':'unknown',status:next.alert?'Pendiente':'En observación',timestamp:stamp(),simulated};tx.set(patternRef,{...result,type:'unknown',times:next.times,lastAlert:next.alert?now:old.data()?.lastAlert||0});tx.set(logRef,{...result,type:'unknown'});if(next.alert)tx.set(db.doc(`alerts/${eventId}`),{...result,notificationStatus:simulated?'simulated':'queued'});return {...result,createdAt:now};});}
exports.simulateSighting=onCall(options,async request=>{const user=uid(request),id=communityId(request);await member(id,user);await quota(user,'demo',30,60000);const plate=text(request.data.plate,8).toUpperCase();if(!/^[A-Z]{3}-\d{4}$/.test(plate))throw new HttpsError('invalid-argument','Placa inválida.');return recordSighting(id,plate,`demo_${randomBytes(16).toString('hex')}`,true);});
exports.triggerAlarm=onCall(options,async request=>{const user=uid(request),id=communityId(request);await member(id,user);await quota(user,'alarm',5,600000);const secret=await db.doc(`user_secrets/${user}`).get();if(!matches(text(request.data.answer,100),secret.data()))throw new HttpsError('permission-denied','La respuesta no coincide.');const ref=await db.collection('alerts').add({communityId:id,triggeredBy:user,type:'manual_alarm',status:'Pendiente',notificationStatus:'queued',timestamp:stamp()});return {id:ref.id};});
exports.registerPush=onCall(options,async request=>{const user=uid(request),id=communityId(request);await member(id,user);const token=text(request.data.token,4096);const tokenId=createHash('sha256').update(token).digest('hex');await db.doc(`communities/${id}/members/${user}/tokens/${tokenId}`).set({communityId:id,token,timestamp:stamp()});return {ok:true};});
// Firebase Functions v2 equivalent of storage.object().onFinalize(). OCR stays on the server.
exports.processCameraClip=onObjectFinalized({...options,memory:'1GiB',timeoutSeconds:120},async event=>{const object=event.data,match=/^cameras\/([\w-]+)\/[^/]+$/.exec(object.name||'');if(!match)return;const id=match[1];if(!/^(video\/|image\/)/.test(object.contentType||''))return;if(Number(object.size)>50*1024*1024)throw new Error('Clip demasiado grande (máximo 50 MB)');const temp=await mkdtemp(path.join(tmpdir(),'autoscan-'));try{const input=path.join(temp,'input'),frame=path.join(temp,'frame.jpg');await admin.storage().bucket(object.bucket).file(object.name).download({destination:input});let buffer;if(object.contentType.startsWith('video/')){await exec(ffmpeg,['-i',input,'-vf','select=eq(n\\,0),scale=1280:-2','-frames:v','1','-y',frame],{timeout:60000});buffer=await readFile(frame);}else buffer=await readFile(input);const [result]=await visionClient.textDetection({image:{content:buffer}});if(result.error?.message)throw new Error(result.error.message);const plates=extractPlates(result.fullTextAnnotation?.text||result.textAnnotations?.[0]?.description||'');for(const plate of plates){const eventId=createHash('sha256').update(`${object.bucket}/${object.name}/${object.generation}/${plate}`).digest('hex');await recordSighting(id,plate,eventId);}}finally{await rm(temp,{recursive:true,force:true});}});
exports.sendAlertPush=onDocumentCreated({...options,document:'alerts/{alertId}'},async event=>{const alert=event.data.data();if(alert.simulated)return;const members=await db.collection(`communities/${alert.communityId}/members`).get();const tokenDocs=(await Promise.all(members.docs.map(m=>m.ref.collection('tokens').get()))).flatMap(s=>s.docs);let sent=0,failed=0;for(let i=0;i<tokenDocs.length;i+=500){const chunk=tokenDocs.slice(i,i+500);const response=await admin.messaging().sendEachForMulticast({tokens:chunk.map(t=>t.data().token),notification:{title:alert.type==='manual_alarm'?'Alarma de emergencia':'AutoScan: patrón detectado',body:alert.plate?`${alert.plate}: 3 o más avistamientos en 7 días`:'Un vecino de tu comunidad solicita atención.'},data:{communityId:alert.communityId,alertId:event.params.alertId},webpush:{notification:{tag:event.params.alertId}}});sent+=response.successCount;failed+=response.failureCount;await Promise.all(response.responses.map((r,j)=>!r.success&&['messaging/registration-token-not-registered','messaging/invalid-registration-token'].includes(r.error?.code)?chunk[j].ref.delete():Promise.resolve()));}await event.data.ref.update({notificationStatus:tokenDocs.length?'processed':'no_tokens',notificationSent:sent,notificationFailed:failed});});
