import React,{useState,useEffect,useRef} from 'react';
import { ShieldCheck, LayoutDashboard, Video, Car, History, Users, Settings, Bell, ArrowUpRight, ArrowRight, Plus, Search, ChevronRight, Radio, Check, CheckCircle2, TriangleAlert, Siren, X, Menu, MapPin, Camera, Activity, LockKeyhole, LogOut, Play, Mail, Smartphone, Eye, Copy, Shield, ScanLine, SlidersHorizontal } from 'lucide-react';
import {configured} from './lib/firebaseConfig';
import * as service from './lib/service';
import {loadDemo,saveDemo,demoProfile,hashAnswer,processDemo,demoCommunity} from './lib/demo';
import {normalizePlate,validPlate} from './lib/pattern';
import { AuthScreen, Onboarding, Catalog, HistoryPage, Alarm, CameraSetup, Flow } from './pages/Screens';
const navigation=[['dashboard','Resumen',LayoutDashboard],['monitoring','Monitoreo',Video],['catalog','Vehículos',Car],['history','Historial',History],['community','Mi comunidad',Users]];
const labels={dashboard:'Resumen de tu comunidad',monitoring:'Monitoreo automático',catalog:'Catálogo de vehículos',history:'Historial de actividad',community:'Mi comunidad',camera:'Configurar cámara',alarm:'Alarma de emergencia',flow:'Así funciona AutoScan'};
const time = t=>new Date(t).toLocaleTimeString('es-EC',{hour:'2-digit',minute:'2-digit'});
const date = t=>new Date(t).toLocaleDateString('es-EC',{day:'numeric',month:'short'});
function Badge({children,tone='green'}){return <span className={`badge ${tone}`}><span className="dot"/>{children}</span>}
function Field({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Empty({children}){return <div className="empty"><Shield size={30}/><p>{children}</p></div>}
export default function App(){
 const [state,setState]=useState(loadDemo),[user,setUser]=useState(null),[mode,setMode]=useState('demo'),[page,setPage]=useState('dashboard'),[authPage,setAuthPage]=useState('login'),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[onboarding,setOnboarding]=useState(false),[invite,setInvite]=useState(''),[push,setPush]=useState(false);
 const stateRef=useRef(state);stateRef.current=state;const userRef=useRef(user);userRef.current=user;
 const notify=message=>setNotice(message);
 useEffect(()=>{saveDemo(state);},[state]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
 useEffect(()=>{if(!configured)return;return service.watchAuth(async account=>{if(!account)return;try{const profile=await service.getProfile(account.uid);setUser({uid:account.uid,name:account.displayName||account.email||'Vecino',...profile});setMode('live');if(profile?.communityId){const community=await service.getCommunity(profile.communityId,account.uid);setState({community,vehicles:[],events:[],patterns:{}});setOnboarding(false);}else{setOnboarding(true);}}catch(e){notify(e.message);}});},[]);
 useEffect(()=>{if(mode!=='live'||!state.community?.id||onboarding)return;let alerts=[],sightings=[],logs=[];const merge=()=>setState(s=>({...s,events:[...alerts,...sightings,...logs].sort((a,b)=>b.createdAt-a.createdAt)}));const error=e=>notify(e.message);const off=[service.watchCollection('vehicles',state.community.id,vehicles=>setState(s=>({...s,vehicles})),error),service.watchCollection('alerts',state.community.id,v=>{alerts=v;merge();},error),service.watchCollection('unrecognized_sightings',state.community.id,v=>{sightings=v.map(x=>({...x,type:'unknown'}));merge();},error),service.watchCollection('sighting_logs',state.community.id,v=>{logs=v;merge();},error)];return()=>off.forEach(fn=>fn());},[mode,state.community?.id,onboarding]);
 async function enterDemo(role='admin'){setMode('demo');setUser(await demoProfile());setState(s=>({...s,community:{...s.community,role}}));setOnboarding(false);setPage('dashboard');}
 async function exit(){if(mode==='live')await service.logout();setUser(null);setAuthPage('login');setPush(false);}
 function navigate(next){setPage(next);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});}
 async function detection(plate){if(mode==='live')return service.call('simulateSighting',{communityId:stateRef.current.community.id,plate});const processed=processDemo(stateRef.current,plate);setState(processed.state);if(processed.result.type==='pattern_detected')notify('Demo: alerta automática registrada para la comunidad');return processed.result;}
 async function resolve(id){try{if(mode==='live')await service.resolveAlert(id);else setState(s=>({...s,events:s.events.map(e=>e.id===id?{...e,status:'Resuelta'}:e)}));notify('Alerta marcada como resuelta');}catch(e){notify(e.message);}}
 const community=state.community,admin=community?.role==='admin',alerts=state.events.filter(e=>['pattern_detected','manual_alarm'].includes(e.type)),pending=alerts.filter(e=>e.status!=='Resuelta').length;
 if(!user)return <AuthScreen authPage={authPage} setAuthPage={setAuthPage} enterDemo={enterDemo} notify={notify} onDemoRegister={async profile=>{setUser(profile);setMode('demo');setOnboarding(true);}}/>;
 if(onboarding)return <Onboarding user={user} mode={mode} notify={notify} exit={exit} done={(community,code)=>{setState({community,vehicles:[],events:[],patterns:{}});setUser(u=>({...u,communityId:community.id}));setInvite(code||'');setOnboarding(false);setPage('community');}}/>;
 return <div className="app"><aside className={`sidebar ${menu?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('dashboard')}}><span className="brand-icon"><ScanLine size={25}/></span>AutoScan<span className="brand-point">.</span></a><div className="workspace-label">ESPACIO DE LA COMUNIDAD</div><div className="community-chip"><div className="community-symbol"><Users size={18}/></div><div><strong>{community.name}</strong><small>{admin?'Administrador':'Residente'}</small></div><ChevronRight size={16}/></div><nav>{navigation.map(([key,title,Icon])=><button key={key} className={page===key?'selected':''} onClick={()=>navigate(key)}><Icon size={20}/>{title}{key==='history'&&pending>0&&<span className="nav-count">{pending}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="security-card"><ShieldCheck size={22}/><strong>La tranquilidad es colectiva.</strong><p>Tu comunidad conectada.<br/>Tu seguridad, en automático.</p><button onClick={()=>navigate('flow')}>Conoce el flujo <ArrowUpRight size={15}/></button></div>{admin&&<button className="side-settings" onClick={()=>navigate('camera')}><Settings size={18}/>Configuración</button>}<button className="profile" onClick={exit}><span className="avatar">{user.name?.slice(0,1)||'V'}</span><span><strong>{user.name}</strong><small>{mode==='demo'?'Sesión de demostración':'Cuenta de Firebase'}</small></span><LogOut size={17}/></button></div></aside>{menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}
 <div className="main-shell"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Abrir menú" onClick={()=>setMenu(true)}><Menu/></button><div className="breadcrumb">Mi comunidad <ChevronRight size={14}/><span>{labels[page]}</span></div><div className="top-actions"><Badge tone={mode==='demo'?'blue':'green'}>{mode==='demo'?'Modo demo':'Firebase conectado'}</Badge><button className="icon-button bell" aria-label="Ver alertas" onClick={()=>navigate('history')}><Bell size={20}/>{pending>0&&<i/>}</button><span className="avatar small">{user.name?.slice(0,1)}</span></div></header>
 <main><div className="demo-strip"><span><Radio size={15}/>{mode==='demo'?'Estás explorando una comunidad de ejemplo. Los eventos y las notificaciones son simulados.':'Datos en vivo de Firebase. El monitor de demostración simula el origen de los eventos.'}</span><button onClick={()=>navigate('flow')}>Ver el flujo <ArrowRight size={14}/></button></div>
 {page==='dashboard'&&<><div className="page-heading"><div><div className="eyebrow">TU COMUNIDAD, MÁS SEGURA</div><h1>Todo bajo control<span className="title-dot">.</span></h1><p>Una mirada a lo que pasa en {community.name}, sin perder la tranquilidad.</p></div><button className="button secondary" onClick={()=>navigate('monitoring')}><Video size={17}/>Ver monitoreo <ArrowUpRight size={16}/></button></div><div className="stats-grid"><Stat title="Vehículos registrados" value={state.vehicles.length.toString().padStart(2,'0')} icon={Car} detail="Parte de tu comunidad"/><Stat title="Avistamientos" value={state.events.filter(e=>e.plate).length.toString().padStart(2,'0')} icon={Eye} detail="Actividad registrada"/><Stat title="Alertas pendientes" value={pending.toString().padStart(2,'0')} icon={Bell} detail={pending?'Requieren revisión':'Tu comunidad está tranquila'} tone="amber"/><Stat title="Cámaras configuradas" value={community.camera?'01':'00'} icon={Video} detail={mode==='demo'?'1 señal de demostración':'Referencia RTSP guardada'} tone="green"/></div>
 <div className="dashboard-grid"><section className="card monitor-card"><div className="card-heading"><div><h2><Video size={19}/>Un ojo en tu comunidad</h2><p>Acceso principal · {community.name}</p></div><Badge tone="blue">Demo automática</Badge></div><Monitor mode={mode} vehicles={state.vehicles} detection={detection} compact/><div className="monitor-footer"><span><span className="dot green-dot"/>Vigilancia sin intervención manual</span><button onClick={()=>navigate('monitoring')}>Abrir monitoreo <ArrowUpRight size={15}/></button></div></section><section className="card activity-card"><div className="card-heading"><div><h2>Actividad reciente</h2><p>Los últimos eventos de tu comunidad</p></div><Activity size={19}/></div><div className="activity-list">{state.events.slice(0,4).map(event=><EventRow key={event.id} event={event}/>)}{!state.events.length&&<Empty>Aún no hay avistamientos.</Empty>}</div><button className="card-link" onClick={()=>navigate('history')}>Ver todo el historial <ArrowRight size={16}/></button></section></div>
 <div className="bottom-grid"><section className="emergency-card"><div className="emergency-icon"><Siren size={28}/></div><div><h2>¿Necesitas ayuda ahora?</h2><p>Activa una alarma para avisar a tu comunidad.</p></div><button className="button danger" onClick={()=>navigate('alarm')}>Activar alarma <ArrowRight size={16}/></button></section><section className="how-card"><span className="how-icon"><ShieldCheck size={23}/></span><div><h3>AutoScan vigila. Tú vives.</h3><p>Descubre cómo detectamos patrones automáticamente.</p><button onClick={()=>navigate('flow')}>Así funciona <ArrowRight size={14}/></button></div></section></div><div className="privacy-line"><LockKeyhole size={13}/>La información se comparte solo dentro de tu comunidad.<span>Diseñado para cuidar, juntos.</span></div></>}
 {page==='monitoring'&&<><PageTitle eyebrow="DETECCIÓN SIN INTERVENCIÓN" title="Tu comunidad, en automático" text="Del movimiento a la alerta: observa cómo AutoScan conecta cada paso."/><div className="monitor-page"><section className="card"><div className="card-heading"><h2><Camera size={19}/>Acceso principal</h2><Badge tone="blue">Origen simulado</Badge></div><Monitor mode={mode} vehicles={state.vehicles} detection={detection}/></section><section className="card explanation"><h2>Qué estás viendo</h2><p>Un evento de movimiento cada 8 segundos. Las placas de ejemplo recorren el mismo flujo de reconocimiento y conteo.</p><div className="rule-box"><strong>3 avistamientos · 7 días</strong><p>Una placa desconocida que se repite alcanza el umbral y genera una alerta.</p></div><p>{mode==='demo'?'El reconocimiento y las notificaciones se simulan en este dispositivo.':'Cada evento llama a una Cloud Function. Esta demo usa una placa simulada; los clips reales se procesan con Cloud Vision.'}</p><button className="button secondary" onClick={()=>navigate('history')}>Ver resultados <ArrowRight size={16}/></button></section></div></>}
 {page==='catalog'&&<Catalog state={state} user={user} mode={mode} notify={notify} setState={setState}/>}
 {page==='history'&&<HistoryPage events={state.events} admin={admin} resolve={resolve}/>}
 {page==='alarm'&&<Alarm user={user} state={state} mode={mode} notify={notify} setState={setState} navigate={navigate}/>}
 {page==='camera'&&admin&&<CameraSetup community={community} mode={mode} notify={notify} setState={setState}/>}
 {page==='community'&&<><PageTitle eyebrow="MÁS SEGUROS, JUNTOS" title={community.name} text={community.zone}/><div className="community-grid"><section className="card form-card"><h2><Users/>Tu comunidad</h2><div className="info-row"><span>Tu rol</span><Badge tone="blue">{admin?'Administrador':'Residente'}</Badge></div><div className="info-row"><span>Ubicación</span><strong>{community.zone}</strong></div><div className="info-row"><span>Cámara</span><strong>{community.camera?.name||'Sin configurar'}</strong></div><p className="muted">Cada comunidad tiene su propio catálogo, actividad y alertas.</p><button className="button secondary" onClick={()=>setOnboarding(true)}>Crear o unirme a otra comunidad <ArrowRight size={15}/></button></section>{admin&&<section className="card form-card"><h2>Invita a tus vecinos</h2><p>Comparte el código. Tus vecinos se unirán con el rol de residente.</p>{invite?<div className="invite-code">{invite}<button className="icon-button" aria-label="Copiar código" onClick={async()=>{try{await navigator.clipboard.writeText(invite);notify('Código copiado');}catch{notify('Selecciona el código y cópialo.');}}}><Copy size={20}/></button></div>:<p className="muted">Por seguridad, el código se muestra solo al generarlo. Renovarlo invalida el anterior.</p>}<button className="button primary" onClick={async()=>{try{if(mode==='live'){const result=await service.call('rotateInvite',{communityId:community.id});setInvite(result.code);}else{const code=crypto.randomUUID().replace(/-/g,'').slice(0,6).toUpperCase();const hash=await hashAnswer(code,community.id);setState(s=>({...s,community:{...s.community,inviteHash:hash}}));setInvite(code);}}catch(e){notify(e.message);}}}><Plus size={16}/>Generar nuevo código</button></section>}<section className="card form-card"><h2><Bell/>Notificaciones</h2><p>{mode==='demo'?'La demo muestra avisos dentro de la app. No envía mensajes a vecinos reales.':'Activa Web Push para recibir alertas aunque cierres la pestaña.'}</p><button className="button secondary" disabled={push} onClick={async()=>{try{if(mode==='demo'){notify('Demo: notificaciones simuladas activadas');setPush(true);}else{await service.enablePush(community.id,notify);setPush(true);notify('Notificaciones activadas');}}catch(e){notify(e.message);}}}>{push?<Check size={17}/>:<Bell size={17}/>} {push?'Notificaciones activadas':'Activar notificaciones'}</button></section></div></>}
 {page==='flow'&&<Flow navigate={navigate} mode={mode}/>}
 </main><nav className="mobile-nav">{navigation.slice(0,4).map(([key,title,Icon])=><button key={key} className={page===key?'selected':''} onClick={()=>navigate(key)}><Icon size={21}/><span>{title}</span></button>)}</nav></div>{notice&&<div className="toast" role="status"><Bell size={18}/><span>{notice}</span><button aria-label="Cerrar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}</div>;
}
function PageTitle({eyebrow,title,text}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div></div>}
function Stat({title,value,icon:Icon,detail,tone='blue'}){return <section className="stat card"><div><span>{title}</span><div className={`stat-icon ${tone}`}><Icon size={20}/></div></div><strong>{value}</strong><small><span className={`dot ${tone}-dot`}/>{detail}</small></section>}
function EventRow({event}){const known=event.type==='recognized',alert=['pattern_detected','manual_alarm'].includes(event.type);return <div className="event-row"><span className={`event-icon ${known?'green':alert?'red':'amber'}`}>{known?<CheckCircle2 size={18}/>:alert?<Bell size={18}/>:<Car size={18}/>}</span><div><strong>{event.type==='manual_alarm'?'Alarma de emergencia':known?'Vehículo reconocido':alert?'Patrón detectado':'Vehículo no reconocido'}</strong><p>{event.plate&&<span className="plate-small">{event.plate}</span>} {known?event.owner:event.type==='manual_alarm'?'Aviso de un vecino':`${event.count||1} avistamientos esta semana`}</p></div><time>{time(event.createdAt)}</time></div>}
function Monitor({vehicles,detection,compact=false,mode}){
 const [phase,setPhase]=useState(0),[result,setResult]=useState(null),[error,setError]=useState(''),[videoFailed,setVideoFailed]=useState(false),[running,setRunning]=useState(true),[clock,setClock]=useState(Date.now());const detectRef=useRef(detection);detectRef.current=detection;const vehiclesRef=useRef(vehicles);vehiclesRef.current=vehicles;const index=useRef(0);
 useEffect(()=>{let alive=true;let busy=false;const timers=new Set();const later=(fn,ms)=>{const t=setTimeout(()=>{timers.delete(t);if(alive)fn();},ms);timers.add(t);};async function cycle(){if(busy)return;busy=true;setError('');setPhase(1);later(()=>setPhase(2),1000);later(async()=>{try{const plate=index.current%3===0?(vehiclesRef.current[0]?.plate||'PBC-1234'):'PBC-1234';index.current++;const next=await detectRef.current(plate);if(!alive)return;setResult(next);setPhase(3);if(next.type==='pattern_detected')later(()=>setPhase(4),1500);}catch(e){if(alive){setError(e.message);setPhase(0);}}finally{busy=false;}},2500);}if(running){later(cycle,1800);const interval=setInterval(cycle,8000);timers.add(interval);}const tick=setInterval(()=>setClock(Date.now()),1000);return()=>{alive=false;timers.forEach(t=>{clearTimeout(t);clearInterval(t);});clearInterval(tick);};},[running]);
 const alerted=result?.type==='pattern_detected',known=result?.type==='recognized';
 return <div className={`monitor ${compact?'compact':''}`}><div className="camera-view"><video autoPlay muted loop playsInline src="/car-clip.mp4" onError={()=>setVideoFailed(true)}/>{videoFailed&&<CameraScene/>}<div className="camera-shade"/><div className="camera-top"><span className="camera-live"><span className="dot"/>{running?'DEMO EN CURSO':'DEMO EN PAUSA'}</span><span>CAM 01 · ACCESO PRINCIPAL</span></div><div className={`detection-box ${phase>=3?(known?'recognized-box':'unknown-box'):''}`}><i/><i/><i/><i/>{phase>=2&&<span>{phase===2?'ANALIZANDO…':result?.plate}</span>}</div><div className="camera-bottom"><span><Camera size={13}/>Escena de demostración {videoFailed?'ilustrada':'en video'}</span><time>{date(clock)} · {time(clock)}</time></div><div className="camera-scan"/></div><div className={`monitor-result ${phase===4?'red':phase>=3?(known?'green':'amber'):''}`}><span className="result-icon">{phase===4?<Bell size={20}/>:phase>=3?(known?<CheckCircle2 size={20}/>:<TriangleAlert size={20}/>):<ScanLine size={20}/>}</span><div><strong>{error?'No se pudo procesar el evento':phase===0?'Monitoreo listo':phase===1?'Movimiento detectado':phase===2?'Leyendo la placa…':phase===4?'Alerta generada automáticamente':known?`Vehículo reconocido · ${result?.plate}`:`Vehículo no reconocido · ${result?.plate}`}</strong><p>{error|| (phase===4?(mode==='demo'?'Demo: aviso simulado a los vecinos':'Consulta la alerta en el historial'):phase>=3?(known?`${result?.owner||'Vecino registrado'} · Registro silencioso`:`${result?.count} avistamientos en 7 días${alerted?' · Umbral alcanzado':' · Sin notificar aún'}`):'El sistema procesa cada evento por sí solo.')}</p></div><span className="auto-tag">AUTO</span></div>{!compact&&<><div className="pipeline">{['Movimiento','Lectura de placa','Validación','Resultado'].map((step,i)=><div key={step} className={phase>i?'done':''}><span>{phase>i?<Check size={13}/>:i+1}</span>{step}</div>)}</div><div className="monitor-controls"><p>Evento automático cada 8 segundos</p><button className="button secondary" onClick={()=>setRunning(r=>!r)}>{running?'Pausar demo':'Reanudar demo'}</button></div></>}</div>;
}
function CameraScene(){return <svg className="camera-scene" viewBox="0 0 900 480" preserveAspectRatio="xMidYMid slice" aria-label="Ilustración de una cámara en el acceso de una urbanización"><defs><linearGradient id="sky" x2="0" y2="1"><stop stopColor="#adbdc3"/><stop offset="1" stopColor="#e2e5df"/></linearGradient><linearGradient id="road" x2="0" y2="1"><stop stopColor="#727b7d"/><stop offset="1" stopColor="#929795"/></linearGradient></defs><rect width="900" height="480" fill="url(#sky)"/><rect y="150" width="900" height="140" fill="#a3aa9a"/>{[0,160,330,670,800].map((x,i)=><g key={x}><rect x={x} y={90+i%2*25} width="140" height="145" fill={i%2?'#c8c6b9':'#dddbce'}/><path d={`M${x-8} ${90+i%2*25}l80 -45 82 45`} fill="#777e76"/><rect x={x+20} y="152" width="28" height="42" fill="#657b7b"/><rect x={x+75} y="152" width="35" height="42" fill="#657b7b"/></g>)}<path d="M370 215h190l290 265H40z" fill="url(#road)"/><path d="M459 250L440 480" stroke="#d8d7bd" strokeWidth="4" strokeDasharray="35 27"/><path d="M0 245L375 215L40 480H0M900 245L550 215L850 480H900" fill="#b9bdb0"/>{[60,190,700,835].map((x,i)=><g key={x}><rect x={x+18} y="114" width="10" height="151" fill="#68776a"/><ellipse cx={x+23} cy="120" rx="48" ry="64" fill={i%2?'#566e5c':'#647b5d'}/><ellipse cx={x+3} cy="108" rx="35" ry="46" fill="#748569"/></g>)}<path d="M0 277L342 222M900 277L571 225" stroke="#737e79" strokeWidth="5"/><g transform="translate(373 261)"><ellipse cx="84" cy="121" rx="107" ry="17" fill="#515957" opacity=".5"/><path d="M10 57l22-55h101l31 53 8 52c-6 19-152 19-162 0z" fill="#d8dfdf"/><path d="M39 12h89l19 40H24z" fill="#44575d"/><path d="M21 63h134l7 39H15z" fill="#bcc8cb"/><rect x="54" y="80" width="62" height="22" rx="3" fill="#eef0e9"/><text x="85" y="95" textAnchor="middle" fontSize="12" fontFamily="monospace" fill="#303f42">PBC-1234</text><path d="M17 72h27M129 72h29" stroke="#eeebc9" strokeWidth="8"/><rect x="9" y="107" width="16" height="22" rx="5" fill="#343e40"/><rect x="147" y="107" width="16" height="22" rx="5" fill="#343e40"/></g><path d="M0 0h900v480H0z" fill="#183b34" opacity=".1"/></svg>}
